config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'
  get 'contact/show'
  get '/contact', to: 'contact#show'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    resources :profiles, only: [:edit, :update, :show]
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end

  get 'auth/:provider/callback', to: 'omniauth#create'

  resources :tracks do
    resources :chords
  end

  namespace :admin do
    root 'sessions#new'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
    resources :users, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/chord.rb
class Chord < ActiveRecord::Base
  belongs_to :track
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :chords
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user
  has_many :chords
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email

  has_secure_password
  has_secure_token

  has_one :profile, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :tracks
  has_many :chords

  before_create :build_profile
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < AdminsController
  skip_before_action :require_admin, only: [:new, :create]

  def create
    if params[:email] == 'admin@mail.ru' && params[:password] == 'qazwsx123'
      session[:admin] = true
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def destroy
    session[:admin] = false
    redirect_to admin_root_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :current_resourse, only: [:destroy]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
  end

  private

  def current_resourse
    @user = User.find(params[:id])
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'admin/application'

  before_action :require_admin

  private

  def require_admin
    redirect_to root_path unless session[:admin]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(token: session[:current_user_id])
  end

  def require_user
    redirect_to root_path unless current_user
  end
  helper_method :current_user
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  def create
    @track = Track.find(params[:track_id])
    @chord = @track.chords.create(chord_params)
    @chord.user_id = current_user.id
    @chord.save
  end

  def destroy
    @track = Track.find(params[:track_id])
    @chord = @track.chords.find(params[:id])
    @chord.destroy
  end

  private

  def chord_params
    params.require(:chord).permit(:user_id, :tablature)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  skip_before_action :require_user
  before_action :current_resources

  def create
    if @user
      @account[user: @user]
    else
      @user = @account.create_user(vk_params)
    end
    @account.save
    session[:current_user_id] = @user.token
    redirect_to root_path
  end

  private

  def current_resources
    @account = Account.find_or_create_by(uid: auth_hash[:uid],
                                         provider: auth_hash[:provider],
                                         email: auth_hash[:info][:email])
    @user = User.find_by(email: auth_hash[:info][:email])
  end

  def vk_params
    {
      email: auth_hash[:info][:email],
      password_digest: auth_hash[:uid]
    }
  end

  def fb_params
    {
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:info][:image],
      password: password,
      password_confirmation: password
    }
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :profile_resource

  def update
    @profile.update(profile_params)
    redirect_to user_profile_url
  end

  def show
    @user = User.find(params[:user_id])
  end

  private

  def profile_resource
    @profile = User.find(params[:user_id]).profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :birtday, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.token
      flash[:success] = 'Welcome'
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:success] = 'Good bye'
    redirect_to root_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :current_track, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_user

  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new
  end

  def create
    @track = current_user.tracks.create(track_params)
    if @track.save
      puts "------>#{@track.user_id.class}"
      redirect_to @track
    else
      render 'new'
    end
  end

  def update
    if @track.update(track_params)
      redirect_to @track
    else
      render 'edit'
    end
  end

  def destroy
    track.destroy
    redirect_to tracks_path
  end

  private

  def track
    @track ||= current_user.tracks.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:name, :user_id, :description)
  end

  def current_track
    @track = Track.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:current_user_id] = @user.token
      redirect_to root_url, notice: 'Thenk you for signing up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def require_user_profile
    current_user == @profile.user
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def permissions_tracks
    current_user == @track.user
 end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view = view
      @images = images
    end

    def html
      # TO FILL IN
    end

    private

    attr_accessor :view, :images
  end
end

app/views/profiles/edit.html.erb
<h1 class='notelist'>Edit profile</h1>
<div class='col-md-9 col-xs-12'>
  <%= form_for [current_user, @profile] do |f| %>
    <div class='col-md-6 col-xs-6'>
      <p>
        <%= f.label :first_name, class: 'notelist' %>
        <%= f.text_field :first_name, required: true, class: 'form-control' %>
      </p>
    </div>
    <div class='col-md-6 col-xs-6'>
      <p>
        <%= f.label :last_name, class: 'notelist' %>
        <%= f.text_field :last_name, required: true, class: 'form-control' %>
      </p>
    </div>
    <div class='col-md-6 col-xs-6'>
      <p>
        <%= f.label :birtday, class: 'notelist' %> 
        <%= f.text_field :birtday, type: 'date', required: true, class: 'form-control' %>
      </p>
    </div>
    <div class='col-md-6 col-xs-6'>
      <p>
        <%= f.label :avatar %><br>
        <%= f.file_field :avatar, { class: 'file-input filestyle', type: 'file' } %>
      </p>
    </div>
    <div class='col-md-12 col-xs-12'>
      <%= f.submit 'Update', class: 'btn btn-success' %>
      <%= link_to 'Back', user_profile_path, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class='col-lg-8 col-sm-12'>
  <div class='card hovercard'>
    <div class='card-background'>
      <%= image_tag @profile.avatar_url(:thumb) %>
    </div>
    <div class='useravatar'>
      <%= image_tag @profile.avatar_url(:thumb), class: 'img-rounded' %>
    </div>
    <div class='card-info'> 
      <span class='card-title'>
        <%= @profile.full_name %>
        <% if require_user_profile %>
          <%= link_to edit_user_profile_url do %>
            <i class='fa fa-1x fa-pencil' aria-hidden='true'></i>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
  <div class='btn-pref btn-group btn-group-justified btn-group-lg' role='group' aria-label='...'>
    <div class='btn-group' role='group'>
      <button type='button' id='stars' class='btn btn-primary' href='#tab1' data-toggle='tab'><span class='glyphicon glyphicon-star' aria-hidden='true'></span>
      <div class='hidden-xs'>Info</div>
      </button>
    </div>
  </div>
  <div class='well'>
    <div class='tab-content'>
      <div class='tab-pane fade in active' id='tab1'>
        <div class='row'>
          <table class='table'>
            <tr>
              <th>
                Full name:
              </th>
              <td>
                <%= @profile.full_name %>
              </td>
            </tr>
            <tr>
              <th>
                Email:
              </th>
              <td>
                <%= @profile.user.email %>
              </td>
            </tr>
            <tr>
              <th>
                Birtday:
              </th>
              <td>
                <%= @profile.birtday %>
              </td>
            </tr>    
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tracks/_chord.html.erb
<% @track.chords.each do |chord| %>
  <div class='row margin-chord' id='chord-<%= chord.id%>'>
    <div class='col-md-10'>
      <h4><%= chord.track.user.email %></h4>
      <div class='jtab'>
        <%= chord.tablature %>
      </div>
    </div>
    <div class='col-md-2'>
      <% if current_user == chord.user %>
        <%= link_to 'Destroy', [chord.track, chord], method: :delete, remote: true, class: 'btn btn-danger pull-right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tracks/_form.html.erb
<%= form_for @track, class: 'form' do |f| %>
  <% if @track.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@track.errors.count, 'error') %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name, class: 'notelist' %> 
    <%= f.text_field :name, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :description, class: 'notelist' %> 
    <%= f.text_area :description, rows: '6', value: '', type: 'text', class: 'form-control' %>
  </p>
  <br>
  <%= f.submit 'Create track', class: 'btn btn-success' %>
  <%= link_to 'Back', tracks_path, class: 'btn btn-danger' %>
<% end %>

app/views/tracks/edit.html.erb
<div class='container col-xs-7 notelist'>
  <p>
    <h4>Edit track</h1>
    <%= render 'form' %>
  </p>
</div>

app/views/tracks/index.html.erb
  <div class='form well col-md-7'>
    <div class='row'>
    <div class='col-md-7'>
      <p>
        <div>
          <h2>Listing Notes
            <% if current_user %>
              <%= link_to 'New track', new_track_path, class: 'btn btn-default' %>
            <% end %>
          </h2>
        </div>
      </p>
    </div>
  </div>
   <div class='row'>
    <div class='col-md-7'>
      <% @tracks.each do |track| %>
      <div class='form-group my-style-articles'>
        <h3><%= track.name %></h3>
        <%= link_to 'Show', track_path(track), class: 'btn btn-default' %>
      </div> 
    <% end %> 
    </div>
  </div>
  </div>
</div>

app/views/tracks/new.html.erb
<div class='container col-xs-7 notelist'>
  <p>
    <h4>Create new track</h1>
    <%= render 'form' %>
  </p>
</div>

app/views/tracks/notes/_a.html.erb
<div class='row'>
  <div class='col-md-12'>
    <center>
    <form action = "" method = "post">
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A '; return false;" value = "A" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Am '; return false;" value = "Am" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A+ '; return false;" value = "A+" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A# '; return false;" value = "A#" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Amaj7 '; return false;" value = "Amaj7" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Asus4 '; return false;" value = "Asus4" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A6 '; return false;" value = "A6" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Am6 '; return false;" value = "Am6" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A7 '; return false;" value = "A7" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Am7 '; return false;" value = "Am7" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A#7 '; return false;" value = "A#7" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Adim7 '; return false;" value = "Adim7" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A7sus4 '; return false;" value = "A7sus4" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='A9 '; return false;" value = "A9" />
      <input type="submit" class='btn btn-primary' onclick="document.getElementById('text').value+='Am9 '; return false;" value = "Am9" />
    </form>
  </div>
</div>

app/views/tracks/notes/_c.html.erb
<div class='row'>
  <div class='col-md-12'>
    <center>
    <form action = "" method = "post">
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C '; return false;" value = "C" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Cm '; return false;" value = "Cm" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C+ '; return false;" value = "C+" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C# '; return false;" value = "C#" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#m '; return false;" value = "C#m" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#+ '; return false;" value = "C#+" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Cmaj7 '; return false;" value = "Cmaj7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#maj7 '; return false;" value = "C#maj7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Csus4 '; return false;" value = "Csus4" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#sus4 '; return false;" value = "C#sus4" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C6 '; return false;" value = "C6" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Cm6 '; return false;" value = "Cm6" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#6 '; return false;" value = "C#6" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#m6 '; return false;" value = "C#m6" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C7 '; return false;" value = "C7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Cm7 '; return false;" value = "Cm7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#7 '; return false;" value = "C#7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#m7 '; return false;" value = "C#m7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='Cdim7 '; return false;" value = "Cdim7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#dim7 '; return false;" value = "C#dim7" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C7sus4 '; return false;" value = "C7sus4" />
      <input type="submit" class='btn btn-success' onclick="document.getElementById('text').value+='C#7sus4 '; return false;" value = "C#7sus4" />
    </form>
  </div>
</div>

app/views/tracks/notes/_d.html.erb
<div class='row'>
  <div class='col-md-12'>
    <center>
    <form action = "" method = "post">
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D '; return false;" value = "D" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Dm '; return false;" value = "Dm" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D+ '; return false;" value = "D+" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D# '; return false;" value = "D#" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#m '; return false;" value = "D#m" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#+ '; return false;" value = "D#+" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Dmaj7 '; return false;" value = "Dmaj7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#maj7 '; return false;" value = "D#maj7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Dsus4 '; return false;" value = "Dsus4" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#sus4 '; return false;" value = "D#sus4" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D6 '; return false;" value = "D6" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Dm6 '; return false;" value = "Dm6" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#6 '; return false;" value = "D#6" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#m6 '; return false;" value = "D#m6" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D7 '; return false;" value = "D7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Dm7 '; return false;" value = "Dm7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#7 '; return false;" value = "D#7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#m7 '; return false;" value = "D#m7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='Ddim7 '; return false;" value = "Ddim7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#dim7 '; return false;" value = "D#dim7" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D7sus4 '; return false;" value = "D7sus4" />
      <input type="submit" class='btn btn-info' onclick="document.getElementById('text').value+='D#7sus4 '; return false;" value = "D#7sus4" />
    </form>
  </div>
</div>

app/views/tracks/notes/_e.html.erb
<div class='row'>
  <div class='col-md-12'>
    <center>
    <form action = "" method = "post">
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E '; return false;" value = "E" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Em '; return false;" value = "Em" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E+ '; return false;" value = "E+" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E# '; return false;" value = "E#" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Emaj7 '; return false;" value = "Emaj7" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Esus4 '; return false;" value = "Esus4" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E6 '; return false;" value = "E6" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Em6 '; return false;" value = "Em6" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E7 '; return false;" value = "E7" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Em7 '; return false;" value = "Em7" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E#7 '; return false;" value = "E#7" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Edim7 '; return false;" value = "Edim7" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='E9 '; return false;" value = "E9" />
      <input type="submit" class='btn btn-danger' onclick="document.getElementById('text').value+='Em9 '; return false;" value = "Em9" />
    </form>
  </div>
</div>

app/views/tracks/notes/_f.html.erb
<div class='row'>
  <div class='col-md-12'>
    <center>
    <form action = "" method = "post">
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F '; return false;" value = "F" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fm '; return false;" value = "Fm" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F+ '; return false;" value = "F+" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F# '; return false;" value = "F#" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fmaj7 '; return false;" value = "Fmaj7" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fsus4 '; return false;" value = "Fsus4" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F6 '; return false;" value = "F6" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fm6 '; return false;" value = "Fm6" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F7 '; return false;" value = "F7" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fm7 '; return false;" value = "Fm7" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F#7 '; return false;" value = "F#7" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fdim7 '; return false;" value = "Fdim7" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='F9 '; return false;" value = "F9" />
      <input type="submit" class='btn btn-warning' onclick="document.getElementById('text').value+='Fm9 '; return false;" value = "Fm9" />
    </form>
  </div>
</div>

app/views/tracks/show.html.erb
<div class='container col-md-12 my-style-content notelist'>
  <div class='row my-style-walls'>
    <div class='row'>
      <div class='col-md-10 wall'>
        <p>
          <h4><%= @track.name %></h4>
        </p> 
        <p>
          <strong>Text song:</strong>
          <p>
            <%= @track.description.html_safe %>
          </p>
        </p>
      </div>  
    </div>
    <%= link_to 'Back', tracks_path, class: 'btn btn-success' %>
    <% if permissions_tracks %>
      <%= link_to 'Update', edit_track_path, class: 'btn btn-warning' %>
      <%= link_to 'Destroy', track_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <% end %>
    <div class='row'>
      <h3>Add chord:</h3>
      <%= form_for([@track, @track.chords.build], remote: true) do |f| %>
        <div id='my-new-chord'>
          <p>
          <div class='row'>
            <div class='col-md-10'>
              <ul class='nav nav-pills'>
                <li role='presentation' class='active'><a href='#tab-1' data-toggle='tab'>A</a></li>
                <li role='presentation'><a href='#tab-2' data-toggle='tab'>C</a></li>
                <li role='presentation'><a href='#tab-3' data-toggle='tab'>D</a></li>
                <li role='presentation'><a href='#tab-4' data-toggle='tab'>E</a></li>
                <li role='presentation'><a href='#tab-5' data-toggle='tab'>F</a></li>
              </ul>
              <div class='tab-content'>
                <div class='tab-pane fade in active' id='tab-1'>
                  <%= render 'tracks/notes/a' %>
                </div>
                <div class='tab-pane fade' id='tab-2'>
                  <%= render 'tracks/notes/c' %>
                </div>
                <div class='tab-pane fade' id='tab-3'>
                  <%= render 'tracks/notes/d' %>
                </div>
                <div class='tab-pane fade' id='tab-4'>
                  <%= render 'tracks/notes/e' %>
                </div>
                <div class='tab-pane fade' id='tab-5'>
                  <%= render 'tracks/notes/f' %>
                </div>
              </div>
              <p>
                <%= f.label :tablature, class: 'notelist' %> 
                <%= f.text_area :tablature, rows: '6', value: '', type: 'text', class: 'form-control text', id: 'text' %>
              </p>
            </div>
          </div>
          <br>
          <%= f.submit 'add note', id: 'new_chord_track', remote: true, class: 'btn btn-success' %>
        </div>
      <% end %>  
    </div>
      <h4>Chords:</h4>
      <div class='col-md-12' id='container-chords'>
        <%= render 'chord' %>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='col-md-6 col-xs-12 col-xs-offset-3'>
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class='error_messages'>
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :email %>
      <br>
      <%= f.text_field :email, autofocus: true, placeholder: 'Email', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, autocomplete: 'off', placeholder: 'Password', required: true, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <br>
      <%= f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'password confirmation', required: true, class: 'form-control' %>
    </p>
      <div class='clear'><%= f.submit 'Create user', class: 'btn btn-success' %></div>
  <% end %>
</div>