config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'
  get 'contact/show'
  get '/contact', to: 'contact#show'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    resources :profiles, only: [:edit, :update, :show]
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end

  get 'auth/:provider/callback', to: 'omniauth#create'

  resources :tracks do
    resources :chords
  end

  namespace :admin do
    root 'sessions#new'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
    resources :users, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/chord.rb
class Chord < ActiveRecord::Base
  belongs_to :track
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :chords
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user
  has_many :chords
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email

  has_secure_password
  has_secure_token

  has_one :profile, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :tracks
  has_many :chords

  before_create :build_profile
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'admin/application'

  before_action :require_admin

  private

  def require_admin
    redirect_to root_path unless session[:admin]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(token: session[:current_user_id])
  end

  def require_user
    redirect_to root_path unless current_user
  end
  helper_method :current_user
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  def create
    @track = Track.find(params[:track_id])
    @chord = @track.chords.create(chord_params)
    @chord.user_id = current_user.id
    @chord.save
  end

  def destroy
    @track = Track.find(params[:track_id])
    @chord = @track.chords.find(params[:id])
    @chord.destroy
  end

  private

  def chord_params
    params.require(:chord).permit(:user_id, :tablature)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  skip_before_action :require_user
  before_action :current_resources

  def create
    if @user
      @account[user: @user]
    else
      @user = @account.create_user(vk_params)
    end
    @account.save
    session[:current_user_id] = @user.token
    redirect_to root_path
  end

  private

  def current_resources
    @account = Account.find_or_create_by(uid: auth_hash[:uid],
                                         provider: auth_hash[:provider],
                                         email: auth_hash[:info][:email])
    @user = User.find_by(email: auth_hash[:info][:email])
  end

  def vk_params
    {
      email: auth_hash[:info][:email],
      password_digest: auth_hash[:uid]
    }
  end

  def fb_params
    {
      email: auth_hash[:info][:email],
      remote_avatar_url: auth_hash[:info][:image],
      password: password,
      password_confirmation: password
    }
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :profile_resource

  def update
    @profile.update(profile_params)
    redirect_to user_profile_url
  end

  def show
    @user = User.find(params[:user_id])
  end

  private

  def profile_resource
    @profile = User.find(params[:user_id]).profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :birtday, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.token
      flash[:success] = 'Welcome'
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:success] = 'Good bye'
    redirect_to root_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :current_track, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_user

  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new
  end

  def create
    @track = current_user.tracks.create(track_params)
    if @track.save
      puts "------>#{@track.user_id.class}"
      redirect_to @track
    else
      render 'new'
    end
  end

  def update
    if @track.update(track_params)
      redirect_to @track
    else
      render 'edit'
    end
  end

  def destroy
    track.destroy
    redirect_to tracks_path
  end

  private

  def track
    @track ||= current_user.tracks.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:name, :user_id, :description)
  end

  def current_track
    @track = Track.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:current_user_id] = @user.token
      redirect_to root_url, notice: 'Thenk you for signing up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def require_user_profile
    current_user == @profile.user
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def permissions_tracks
    current_user == @track.user
 end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view = view
      @images = images
    end

    def html
      # TO FILL IN
    end

    private

    attr_accessor :view, :images
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitar</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://jtab.tardate.com/javascripts/jquery.js" type="text/javascript"></script>
  <script src="http://jtab.tardate.com/javascripts/raphael.js" type="text/javascript"></script>
  <script src="http://jtab.tardate.com/javascripts/jtab.js" type="text/javascript"></script>
</head>
<body>
  <%= render 'shared/header' %>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_header.html.erb
<nav class='navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-1x fa-music" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav navbar-rleft'>
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <li>
          <%= link_to 'All tracks', tracks_path %>
        </li>
        <li>
          <%= link_to 'Contacts', contact_path %>
        </li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if current_user %>
          <li>
            <%= link_to user_profile_path(current_user, current_user.profile) do %>
              <% if current_user.profile.first_name == nil %>
                <%= current_user.email %>
              <% else %>
                <%= current_user.profile.full_name %>
              <% end %>
              <%= image_tag current_user.profile.avatar.url(:small), class: 'img-circle profile_small' %>
            <% end %>
          </li>
          <li>
            <%= link_to 'Log out', logout_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign up', signup_path %>
          </li>
          <li>
            <%= link_to 'Log In', login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>